Algoritmo "idade"
// Disciplina   : [LLógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita a idade do usuário em anos, meses e dias, calcula tudo e exibe o resultado em dias
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2025
Var
// Seção de Declarações das variáveis 
anos : inteiro
meses : inteiro
dias : inteiro
total : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo