Algoritmo "sucessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita um número e exibe seu sucessor
// Autor(a)    : Laura Sena
// Data atual  : 28/08/2025
Var
// Seção de Declarações das variáveis
num : inteiro
suc : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreva ("Digite um número: ")
  leia (num)
  suc <- num+1
  escreva ("O sucessor de", num, " é:", suc)

Fimalgoritmo